# Generated by Django 5.2 on 2025-05-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('NOT_DONE', 'Not Done')], default='PENDING', max_length=20),
        ),
    ]
